title: "DFG Network CCS & Online Protest"
description: "Documentation site for the DFG network on Computational Communication Science and Online Protest"
lang: en
url: ""
baseurl: ""
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
search_enabled: true
heading_anchors: true
nav_sort: case_insensitive
color_scheme: light
back_to_top: true
back_to_top_text: "Back to top"

defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-remote-theme


